<link rel="stylesheet" href="/css/daterangepicker.css" />
<link rel="stylesheet" href="/assets/color-picker/css/bootstrap-colorpicker.css" />

<script src="/js/parser-eval.js"></script>
<script type="text/javascript" src="/js/jquery.validate.min.js"></script>
<script src="/js/moment.js"></script>
<script src="/js/daterangepicker.js"></script>
<script src="/js/jquery.number.js"></script>
<script src="/assets/color-picker/js/bootstrap-colorpicker.js"></script>


<script type="text/javascript" charset="utf-8">
    $(document).ready(function() {
        
        $("#reporte_form").validate({
            rules: {
                nombre: {
                    required: true,
                    minlength: 5,
                    remote: {
                        url: "/reporte/checkName",
                        type: "POST",
                        async: false,
                        data:{
                            id_reporte: function() {
                                return $( "#id_reporte" ).val();
                            },
                            id_plantilla: function() {
                                return $( "#id_plantilla" ).val();
                            },
                            nombre: function() {
                                return $( "#nombre" ).val();
                            }
                        }
                    }
                },
                descripcion: {
                    minlength: 5
                },
                periodo: {
                    required: true
                }
            },
            messages: {
                nombre: {
                    required: "Ingrese un nombre para la reporte.",
                    minlength: "El nombre de la reporte debe contener al menos 5 carácteres.",
                    remote: "El nombre no se encuentra disponible."
                },
                descripcion: {
                    minlength: "La descripción debe contener al menos 5 carácteres."
                },
                periodo: {
                    required: "El período no puede estar vacío."
                }
            },
            invalidHandler: function(form, validator) {
                var errors = validator.numberOfInvalids();
                if (errors) {
                    validator.errorList[0].element.focus();
                }
            }
        });

        $('#periodo').dateRangePicker({
            format: 'DD/MM/YYYY',
            separator: ' - ',
            minDate: new Date()
        });

        $.executeFetch({
            action: "/plantilla/fetch",
            data: {id_plantilla: $("#id_plantilla").val()},
            method: "POST",
            dataType:"json",
            success: function(data){
                $("#plantillaBC").html(data.nombre);
                $("#plantillaBC").attr("href","/plantilla?id="+data.id);
                $("#reportesBC").attr("href","/reportes?id="+data.id);
                if($("#id_reporte").val() === "0"){
                    $("#reporteBC").attr("href","/reporte?id_plantilla="+data.id);
                }else{
                    $("#reporteBC").attr("href","/reporte?id="+$("#id_reporte").val()+"&id_plantilla="+data.id);
                }
            },
            errorMsg: "Ocurrió un error al obtener la plantilla."
        });

        var fetch = function(){
            $.executeFetch({
                action: "/reporte/fetch",
                data: {id_reporte: $("#id_reporte").val()},
                method: "POST",
                dataType:"json",
                success: function(data){
                    $("#headerSection").html(data.nombre);
                    $("#reporteBC").html(data.nombre);
                    $("#reporteBC").attr("href","/reportes?id="+data.id);
                    $("#nombre").val(data.nombre);
                    $("#descripcion").val(data.descripcion);
                    $("#periodo").val(data.periodo);
                },
                errorMsg: "Ocurrió un error al obtener la reporte."
            });
        }

        $("#addReporteBT").click( function( e ){
            $.executePostValid({
                form: $("#reporte_form"),
                action: "/reporte/update",
                method: "POST",
                dataType:"json",
                success: function(data){
                    $("#id_reporte").val(data.id);
                    $("#headerSection").html(data.nombre);
                    $("#reporteBC").html(data.nombre);
                    $("#reporteBC").attr("href","/reporte?id="+data.id);
                    //refreshTable
                    refreshTable();
                    $("#camposSection").show(500);
//                    $("#previewSection").show(500);
                },
                successMsg: "Reporte guardada.",
                errorMsg: "Ocurrió un error al guardar la reporte."
            });
        });

        /******************************************** CAMPOS ************************************************/

        var table;

        var refreshTable = function(){
            if(table){
                table.destroy();
            }
            $.executeFetch({
                action: "/campo/fetchAll",
                method: "POST",
                dataType:"json",
                data: {id_plantilla: $("#id_plantilla").val()},
                success: function(data){
                    campos = data;
                    var html = "";
                    data.forEach(function(campo) {

                        if(campo.id_repetir_campo){
                            if(campo.id_repetir_campo === "1"){
                                campo.tipo_campo = "Repetir Fecha - " + campo.tipo_campo;
                            }else{
                                campo.tipo_campo = "Repetir Veces - " + campo.tipo_campo;
                            }
                        }

                        var campoChecked = "";
                        if(campo.activo === "1"){
                            campoChecked = "checked";
                        }
                        var up = "";
                        if(parseInt(campo.orden) !== 1){
                            up = "<i class='icon_sm arrow_up_alt upBT' id='up_"+campo.id+"' orden='"+campo.orden+"'></i> ";
                        }
                        var down = "";
                        if(parseInt(campo.orden) < data.length){
                            down = "<i class='icon_sm arrow_down_alt downBT' id='down_"+campo.id+"' orden='"+campo.orden+"'></i> ";
                        }

                        var colorPicker = $("#colorPickerLayout").html().replaceAll("?colorId","cp_"+campo.id).replace("?colorValue", campo.color);

                        html += "<tr id='tr_"+campo.id+"'>"
                        + "<td class='text-center'>" + up + campo.orden + down + "</td>"
                        + "<td class='text-center'><input type='checkbox' class='camposCB' id='cb_"+campo.id+"' "+campoChecked+"/></td>"
                        + "<td>"+colorPicker+"</td>"
                        + "<td>"+campo.nombre+"</td>"
                        + "<td>"+campo.tipo_campo+"</td>"
                        + "<td>"+campo.prefijo+"</td>"
                        + "<td>"+campo.sufijo+"</td>"
                        + "<td>"+campo.valor+"</td>"
                        + "</tr>\n";

                    });
                    //Main table
                    $("#mainTableBody").html(html);
                    table = $('#mainTable').DataTable({
                        "columns": [
                            { "width": "10%" },
                            { "width": "5%" },
                            { "width": "20%" },
                            { "width": "25%" },
                            { "width": "15%" },
                            { "width": "10%" },
                            { "width": "10%" },
                            { "width": "5%" }
                        ],
                        "bSort": false,
                        "language": {
                            "url": "/app/lang/Spanish.json"
                        },
                        "bPaginate": false
                    });
                    $("#mainTable tbody tr").hover( function( e ) {
                        if ( $(this).hasClass('row_selected') ) {
                            $(this).removeClass('row_selected');
                        }
                        else {
                            table.$('tr.row_selected').removeClass('row_selected');
                            $(this).addClass('row_selected');
                        }
                    });
                    refreshTableActions();
                },
                errorMsg: "Ocurrió un error al obtener los campos."
            });
        }

        var refreshTableActions = function(){
            //Activar campos
            $(".camposCB").click(function(e){
                var id = $(this).attr("id").substring(3);
                if($(this).is(":checked")) {
                    $.executeFetch({
                        action: "/campo/updateActivo",
                        data: {
                            id_campo: id,
                            activo: true
                        },
                        method: "POST",
                        dataType:"json",
                        success: function(){},
                        successMsg: "Campo activado.",
                        errorMsg: "Ocurrió un error al activar el campo."
                    });
                }else{
                    $.executeFetch({
                        action: "/campo/updateActivo",
                        data: {
                            id_campo: id,
                            activo: false
                        },
                        method: "POST",
                        dataType:"json",
                        success: function(){},
                        successMsg: "Campo desactivado.",
                        errorMsg: "Ocurrió un error al desactivar el campo."
                    });
                }
            });
            //Color
            $('.colorPicker').colorpicker({
                component: "#colorPreview"
            });
            $('.saveColor').click(function(e){
                var colorId = $(this).attr("color-id");
                var id = $("#"+colorId).attr("id").substring(3);
                var color = $("#"+colorId).val();
                $.executeFetch({
                    action: "/campo/updateColor",
                    data: {
                        id_campo: id,
                        color: color
                    },
                    method: "POST",
                    dataType:"json",
                    success: function(){},
                    successMsg: "Campo desactivado.",
                    errorMsg: "Ocurrió un error al desactivar el campo."
                });
            });
            //Ordenar campos hacia arriba
            $(".upBT").click(function(e){
                var id = $(this).attr("id").substring(3);
                var orden = parseInt($(this).attr("orden"));
                $.executeFetch({
                    action: "/campo/orden",
                    data: {
                        id: id,
                        id_plantilla: $("#id_plantilla").val(),
                        orden: orden,
                        action: 'up'
                    },
                    method: "POST",
                    dataType:"json",
                    success: function(){
                        refreshTable();
                    },
                    successMsg: "Campo ordenado.",
                    errorMsg: "Ocurrió un error al ordenar el campo."
                });
            });
            //Ordenar campos hacia abajo
            $(".downBT").click(function(e){
                var id = $(this).attr("id").substring(5);
                var orden = parseInt($(this).attr("orden"));
                $.executeFetch({
                    action: "/campo/orden",
                    data: {
                        id: id,
                        id_plantilla: $("#id_plantilla").val(),
                        orden: orden,
                        action: 'down'
                    },
                    method: "POST",
                    dataType:"json",
                    success: function(){
                        refreshTable();
                    },
                    successMsg: "Campo ordenado.",
                    errorMsg: "Ocurrió un error al ordenar el campo."
                });
            });
        }

        if(parseInt($("#id_reporte").val()) !== 0){
            fetch();
            refreshTable();
            $("#camposSection").show(500);
        }

        /******************************************** REPORTE ************************************************/

        $("#generarReporteBT").click(function(e){
            refreshReporte();
            $("#previewSection").show(500);
        });

        var table2;
        var colsTmpl;
        var refreshReporte = function(){
            colsTmpl = new Array();
            $.executeFetch({
                action: "/campo/fetchAll",
                method: "POST",
                dataType:"json",
                data: {id_plantilla: $("#id_plantilla").val()},
                success: function(data){
                    var ths = "";
                    var contenido = "";

                    //static
                    ths += "<th>No. Empleado</th>";
                    ths += "<th>Nombre</th>";
                    ths += "<th>Fecha Ingreso</th>";
                    ths += "<th>Horario</th>";
                    ths += "<th>Unidad de Negocio</th>";
                    ths += "<th>Puesto</th>";
                    ths += "<th>Campaña</th>";
                    ths += "<th>Jefe Inmediato</th>";
                    ths += "<th>Sueldo Diario</th>";
                    ths += "<th>Sueldo Quincenal</th>";

                    //periodo
                    var periodoCols = new Array();
                    var fechas = $("#periodo").val().split(" - ");
                    var inicio = fechas[0];
                    var fin = fechas[1];
                    inicio = inicio.split("/");
                    fin = fin.split("/");
                    inicio = new Date(parseInt(inicio[2]),parseInt(inicio[1])-1,parseInt(inicio[0]));
                    fin = new Date(parseInt(fin[2]),parseInt(fin[1])-1,parseInt(fin[0]));
                    while(inicio <= fin){
                        var label = inicio.toLocaleString().split(" ");
                        ths += "<th>"+label[0]+"</td>";
                        periodoCols.push(label[0]);
                        var newDate = inicio.setDate(inicio.getDate() + 1);
                        inicio = new Date(newDate);
                    }

                    //cols
                    data.forEach(function(campo) {

                        if(campo.activo === "1"){
                            ths += "<th style='background-color: "+campo.color+"'>"+campo.nombre+"</th>";
                            if(campo.id_tipo_campo === "4"){
                                contenido = "<input type='text' class='form-control'/>";
                            }else if(campo.id_tipo_campo === "1"){
                                var opts = campo.valor.split("|");
                                var optsHtml = "";
                                for(var i=0; i<opts.length; i++){
                                    optsHtml += "<option value='"+opts[i]+"'>"+opts[i]+"</option>";
                                }
                                contenido = "<select class='form-control'>"+ optsHtml + "</select>";
                            }else{
                                contenido = campo.prefijo+campo.valor+campo.sufijo;
                            }

                            colsTmpl.push(contenido);
                        }

                    });

                    var tableWidth = (10 + periodoCols.length + colsTmpl.length) * 200;
                    $("#previewTable").attr("width", tableWidth + "px");
                    $.executeFetch({
                        action: "/empleado/fetchAll",
                        method: "POST",
                        dataType:"json",
                        data: {id_tipo_empleado: $("#id_tipo_empleado").val()},
                        success: function(empleados){

                            var trs = "";
                            empleados.forEach(function(empleado) {
                                //static
                                trs += "<tr>";
                                trs += "<td>"+empleado.id_rh+"</td>";
                                trs += "<td>"+empleado.nombre+"</td>";
                                trs += "<td>"+empleado.fecha_ingreso+"</td>";
                                trs += "<td>"+empleado.horario+"</td>";
                                trs += "<td>"+empleado.unidad_negocio+"</td>";
                                trs += "<td>"+empleado.tipo_empleado+"</td>";
                                trs += "<td>"+empleado.campana+"</td>";
                                trs += "<td>"+empleado.jefe+"</td>";
                                trs += "<td>$ " + $.number(empleado.sueldo_diario, 2) + "</td>";
                                trs += "<td>$ " + $.number(empleado.sueldo_quincenal, 2) + "</td>";
                                //periodo
                                var selectLayout;
                                periodoCols.forEach(function(periodo) {
                                    selectLayout = $("#selectLayout").html().replace("?campoId","periodo_"+empleado.id+"_"+periodo);
                                    trs += "<td>"+selectLayout+"</td>";
                                });
                                //cols
                                colsTmpl.forEach(function(col) {
                                    trs += "<td>"+col+"</td>";
                                });
                                trs += "</tr>";
                            });

                            if(data.length > 0 && empleados.length > 0){
                                if(table2)
                                    table2.destroy();

                                //Preview table
                                $("#previewTableHR").html(ths);
                                $("#previewTableBody").html(trs);
                                table2 = $('#previewTable').DataTable({
                                    "scrollY": 400,
                                    "scrollX": true,
                                    "bPaginate": false,
                                    "language": {
                                        "url": "/app/lang/Spanish.json"
                                    }
                                });
                                $("#previewTable tbody tr").hover( function( e ) {
                                    if ( $(this).hasClass('row_selected') ) {
                                        $(this).removeClass('row_selected');
                                    }
                                    else {
                                        table2.$('tr.row_selected').removeClass('row_selected');
                                        $(this).addClass('row_selected');
                                    }
                                });

                            }

                        },
                        errorMsg: "Ocurrió un error al obtener los campos."
                    });
                },
                errorMsg: "Ocurrió un error al obtener los campos."
            });
        }

    });

    function reverse(s){
        return s.split("").reverse().join("");
    }

    function parseInteger(integer){
        try{
            return parseInt(integer);
        }catch(e){
            return false;
        }
    }

</script>

<div class="row">
    <div class="col-lg-12">

        <section class="panel">
            <header class="panel-heading" id="headerSection">
                Nuevo Reporte
            </header>
            <div class="panel-body">
                <div class="form">
                    <form class="form-validate form-horizontal" id="reporte_form">
                        <input type="hidden" id="id_reporte" name="id_reporte" value="<?php if($id){ echo $id; }else{ echo "0"; } ?>"/>
                        <input type="hidden" id="id_plantilla" name="id_plantilla" value="<?php echo $id_plantilla; ?>"/>
                        <input type="hidden" id="id_tipo_empleado" name="id_tipo_empleado" value="<?php echo $id_tipo_empleado; ?>"/>
                        <div class="form-group">
                            <label class="control-label col-lg-2">Nombre <span class="required">*</span></label>
                            <div class="col-lg-5">
                                <input class="form-control" id="nombre" name="nombre" minlength="5" type="text"/>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-lg-2">Descripción</label>
                            <div class="col-lg-5">
                                <textarea class="form-control" id="descripcion" name="descripcion" rows="6"></textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-lg-2">Período</label>
                            <div class="col-lg-2">
                                <div class='input-group date'>
                                    <input type='text' class="form-control" id="periodo" name="periodo"/>
                                    <span class="input-group-addon">
                                        <span class="glyphicon glyphicon-calendar"></span>
                                    </span>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-lg-offset-2 col-lg-10">
                                <button class="btn btn-primary" type="button" id="addReporteBT">Guardar</button>
                                <a class="btn btn-default" href="/reportes?id=<?php echo $id_plantilla; ?>">Regresar</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </section>

        <section class="panel no-display" id="camposSection">
            <header class="panel-heading">
                Campos Disponibles
                <a id="generarReporteBT" class="btn  btn-primary pull-right">
                    Generar Reporte
                </a>
            </header>
            <div class="panel-body">
                <table id="mainTable" class="table table-bordered" cellspacing="0" width="100%">
                    <thead>
                    <tr>
                        <th>Orden</th>
                        <th>Activo</th>
                        <th>Color</th>
                        <th>Nombre</th>
                        <th>Tipo</th>
                        <th>Prefijo</th>
                        <th>Sufijo</th>
                        <th>Valor</th>
                    </tr>
                    </thead>
                    <tbody id="mainTableBody"></tbody>
                </table>
            </div>
        </section>

        <section class="panel no-display" id="previewSection">
            <header class="panel-heading">
                <i class='icon_md icon_table'></i>
                Vista Previa&nbsp;&nbsp;
                <i class='icon_md icon_question_alt' id="previewHint"></i>
            </header>
            <div class="panel-body">
                <table id="previewTable" class="table table-bordered" cellspacing="0">
                    <thead id="previewTableHead">
                        <tr id="previewTableHR"></tr>
                    </thead>
                    <tbody id="previewTableBody"></tbody>
                </table>
            </div>
        </section>

    </div>
</div>

<div id="expressionSelectLayout" class="hidden">
    <div class="form-group">
        <label class="control-label col-lg-4">?campoLabel</label>
        <div class="col-lg-8" id="selectLayout">
            <select class="form-control" id="?campoId" name="?campoName">
                <option value="A">Asistencia</option>
                <option value="F">Falta</option>
                <option value="I">Incapacidad</option>
                <option value="V">Vacaciones</option>
            </select>
        </div>
    </div>
</div>

<div id="colorPickerLayout" class="hidden">
    <div class="input-group colorPicker">
        <span id="colorPreview" class="input-group-addon"><i></i></span>
        <input type="text" id="?colorId" class="form-control" value="?colorValue"/>
        <span class="input-group-addon"><i class="icon_sm icon_check_alt saveColor" color-id="?colorId"></i></span>
    </div>
</div>