<?php
  use Application\Model\Application;
  $session = new \Zend\Session\Container('user');
  $user = $session->user;
?>

<script type="text/javascript" charset="utf-8">
  $(document).ready(function () {

    var table;

    var refreshTable = function () {
      $.executeFetch({
        action: "/plantilla/fetchAll",
        method: "POST",
        dataType: "json",
        success: function (data) {
          var html = "";
          var no = 1;
          data.forEach(function (plantilla) {
            html += "<tr id='tr_" + plantilla.id + "'>";
            html += "<td class='text-center'><input type='checkbox'></td>";
            html += "<td>" + no++ + "</td>";
            html += "<td>" + plantilla.nombre + "</td>";
            html += "<td>" + plantilla.unidad_negocio + "</td>";
            html += "<td>" + plantilla.tipo_empleado + "</td>";
            if($("#id_rol_usuario").val() == ROL_ADMINISTRADOR || $("#id_rol_usuario").val() == ROL_ADMINISTRADOR_PLANTILLAS){
              html += "<td class='text-center'>";
              html += "<a href='/plantilla?id=" + plantilla.id + "'>";
              html += "<i class='icon-md icon_search_alt'></i>";
              html += "</a>";
              html += "</td>";
              html += "<td class='text-center'>";
              html += "<a href='#eliminarModal' data-toggle='modal' data-id='" + plantilla.id + "'>";
              html += "<i class='icon-md icon_trash'></i>";
              html += "</a>";
              html += "</td>";
            }else{
              html += "<td class='text-center'>";
              html += "<a href='/reportes?id=" + plantilla.id + "'>";
              html += "<i class='icon-md icon_search_alt'></i>";
              html += "</a>";
              html += "</td>";
            }
            html += "</tr>\n";
          });
          $("#mainTableBody").html(html);
          var lastIdx = null;
          var colWidths;
          if($("#id_rol_usuario").val() == ROL_ADMINISTRADOR || $("#id_rol_usuario").val() == ROL_ADMINISTRADOR_PLANTILLAS){
            colWidths = [
              {"width": "5%"},
              {"width": "5%"},
              {"width": "30%"},
              {"width": "20%"},
              {"width": "30%"},
              {"width": "5%"},
              {"width": "5%"}
            ];
          }else{
            colWidths = [
              {"width": "5%"},
              {"width": "5%"},
              {"width": "35%"},
              {"width": "20%"},
              {"width": "30%"},
              {"width": "5%"}
            ];
          }
          table = $('#mainTable').DataTable({
            "columns": colWidths,
            "language": {
              "url": "/app/lang/Spanish.json"
            },
            "order": [[1, "asc"]],
            "aoColumnDefs": [
              {'bSortable': false, 'aTargets': [0]}
            ]
          });
          $("#mainTable tbody tr").hover(function (e) {
            if ($(this).hasClass('row_selected')) {
              $(this).removeClass('row_selected');
            }
            else {
              table.$('tr.row_selected').removeClass('row_selected');
              $(this).addClass('row_selected');
            }
          });
        },
        errorMsg: "Ocurrió un error al obtener las plantillas."
      });
    }

    refreshTable();

    $("#eliminarBT").click(function (e) {
      $.executePost({
        action: "/plantilla/remove",
        method: "POST",
        data: {id_plantilla: $("#id_plantilla").val()},
        dataType: "json",
        success: function (data) {
          table.row('#tr_' + $("#id_plantilla").val()).remove().draw(false);
        },
        successMsg: "Plantilla eliminada.",
        errorMsg: "Ocurrió un error al eliminar la plantilla."
      });
    });

    $('#eliminarModal').on('show.bs.modal', function (e) {
      var id_plantilla = $(e.relatedTarget).data('id');
      $("#id_plantilla").val(id_plantilla);
    });

  });
</script>

<div class="row">
  <div class="col-lg-12">
    <section class="panel">
      <header class="panel-heading">
        Plantillas Disponibles
        <?php if ($user['id_rol_usuario'] == Application::ROL_ADMINISTRADOR
          || $user['id_rol_usuario'] == Application::ROL_ADMINISTRADOR_PLANTILLAS) { ?>
          <a href="/plantilla" class="btn  btn-primary pull-right">
            Agregar
          </a>
        <?php } ?>
      </header>
      <div class="panel-body">
        <table id="mainTable" class="table table-bordered" cellspacing="0" width="100%">
          <thead>
          <tr>
            <th>Seleccionar</th>
            <th>No.</th>
            <th>Nombre</th>
            <th>Unidad de Negocio</th>
            <th>Tipo Empleado</th>
            <th>Consultar</th>
            <?php if ($user['id_rol_usuario'] == Application::ROL_ADMINISTRADOR
              || $user['id_rol_usuario'] == Application::ROL_ADMINISTRADOR_PLANTILLAS) { ?>
            <th>Eliminar</th>
            <?php } ?>
          </tr>
          </thead>
          <tbody id="mainTableBody"></tbody>
        </table>
      </div>
    </section>
  </div>
</div>

<div aria-hidden="true" aria-labelledby="eliminarModal" role="dialog" tabindex="-1" id="eliminarModal"
     class="modal fade">
  <div class="modal-dialog modal-msg">
    <div class="modal-content">
      <div class="modal-header">
        <button aria-hidden="true" data-dismiss="modal" class="close" type="button">x</button>
        <h4 class="modal-title">Eliminar</h4>
      </div>
      <div class="modal-body">
        <form class="form-horizontal" role="form">
          <input type="hidden" id="id_plantilla" name="id_plantilla"/>

          <div class="form-group modal-msg-label">
            <div class="col-lg-offset-1 col-lg-10">
              <span>¿Está seguro que desea eliminar la plantilla?</span>

              <div class="spacer-sm"></div>
              <div class="alertFont"><i class="icon_error-triangle"></i><span> Al eliminar la plantilla eliminará todos los campos contenidos en ella.</span>
              </div>
              <div class="spacer-sm"></div>
            </div>
          </div>
          <div class="form-group">
            <div class="col-lg-offset-1 col-lg-12">
              <button type="button" id="eliminarBT" class="btn btn-primary" data-dismiss="modal">Eliminar</button>
              <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

