<script type="text/javascript" charset="utf-8">
    $(document).ready(function() {

        var table;

        var refreshTable = function(){
            $.executeFetch({
                action: "/plantilla/fetchAll",
                method: "POST",
                dataType:"json",
                success: function(data){
                    var html = "";
                    var no = 1;
                    data.forEach(function(plantilla) {
                        html += "<tr id='tr_"+plantilla.id+"'>"
                        + "<td class='text-center'><input type='checkbox'></td>"
                        + "<td>"+no+++"</td>"
                        + "<td>"+plantilla.nombre+"</td>"
                        + "<td>"+plantilla.unidad_negocio+"</td>"
                        + "<td>"+plantilla.tipo_empleado+"</td>"
                        + "<td class='text-center'>"
                        + "<a href='/plantilla?id="+plantilla.id+"'>"
                        + "<i class='icon_md icon_search_alt'></i>"
                        + "</a>"
                        + "</td>"
                        + "<td class='text-center'>"
                        + "<a href='#eliminarModal' data-toggle='modal' data-id='"+plantilla.id+"'>"
                        + "<i class='icon_md icon_trash'></i>"
                        + "</a>"
                        + "</td>"
                        + "</tr>\n";
                    });
                    $("#mainTableBody").html(html);
                    var lastIdx = null;
                    table = $('#mainTable').DataTable({
                        "columns": [
                            { "width": "5%" },
                            { "width": "5%" },
                            { "width": "30%" },
                            { "width": "20%" },
                            { "width": "30%" },
                            { "width": "5%" },
                            { "width": "5%" }
                        ],
                        "language": {
                            "url": "/app/lang/Spanish.json"
                        },
                        "order": [[ 1, "asc" ]],
                        "aoColumnDefs": [
                            { 'bSortable': false, 'aTargets': [0]}
                        ]
                    });
                    $("#mainTable tbody tr").hover( function( e ) {
                        if ( $(this).hasClass('row_selected') ) {
                            $(this).removeClass('row_selected');
                        }
                        else {
                            table.$('tr.row_selected').removeClass('row_selected');
                            $(this).addClass('row_selected');
                        }
                    });
                },
                errorMsg: "Ocurrió un error al obtener las plantillas."
            });
        }

        refreshTable();

        $("#eliminarBT").click( function( e ){
            $.executePost({
                action: "/plantilla/remove",
                method: "POST",
                data: {id_plantilla: $("#id_plantilla").val()},
                dataType:"json",
                success: function(data){
                    table.row('#tr_'+$("#id_plantilla").val()).remove().draw( false );
                },
                successMsg: "Plantilla eliminada.",
                errorMsg: "Ocurrió un error al eliminar la plantilla."
            });
        });

        $('#eliminarModal').on('show.bs.modal', function(e) {
            var id_plantilla = $(e.relatedTarget).data('id');
            $("#id_plantilla").val(id_plantilla);
        });

    });
</script>

<div class="row">
    <div class="col-lg-12">
        <section class="panel">
            <header class="panel-heading">
                Plantillas Disponibles
                <a href="/plantilla" class="btn  btn-primary pull-right">
                    Agregar
                </a>
            </header>
            <div class="panel-body">
                <table id="mainTable" class="table table-bordered" cellspacing="0" width="100%">
                    <thead>
                    <tr>
                        <th>Seleccionar</th>
                        <th>No.</th>
                        <th>Nombre</th>
                        <th>Unidad de Negocio</th>
                        <th>Tipo Empleado</th>
                        <th>Consultar</th>
                        <th>Eliminar</th>
                    </tr>
                    </thead>
                    <tbody id="mainTableBody"></tbody>
                </table>
            </div>
        </section>
    </div>
</div>

<div aria-hidden="true" aria-labelledby="eliminarModal" role="dialog" tabindex="-1" id="eliminarModal" class="modal fade">
    <div class="modal-dialog modal-msg">
        <div class="modal-content">
            <div class="modal-header">
                <button aria-hidden="true" data-dismiss="modal" class="close" type="button">x</button>
                <h4 class="modal-title">Eliminar</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal" role="form">
                    <input type="hidden" id="id_plantilla" name="id_plantilla"/>
                    <div class="form-group modal-msg-label">
                        <div class="col-lg-offset-1 col-lg-10">
                            <span>¿Está seguro que desea eliminar la plantilla?</span>
                            <div class="spacer-sm"></div>
                            <div class="alertFont"><i class="icon_error-triangle"></i><span> Al eliminar la plantilla eliminará todos los campos contenidos en ella.</span></div>
                            <div class="spacer-sm"></div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-offset-1 col-lg-12">
                            <button type="button" id="eliminarBT" class="btn btn-primary" data-dismiss="modal">Eliminar</button>
                            <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

