<div class="container">
  <form class="login-form" method="POST" name="User" action="/auth/authenticate" id="User">
    <div class="login-wrap">
      <p class="login-img"><i class="icon_lock_alt"></i></p>

      <div class="input-group">
        <span class="input-group-addon"><i class="icon_profile"></i></span>
        <input type="text" class="form-control" placeholder="Username" name="username" required="required" autofocus>
      </div>
      <div class="input-group">
        <span class="input-group-addon"><i class="icon_key_alt"></i></span>
        <input type="password" class="form-control" placeholder="Password" name="password" required="required">
      </div>
      <input type="hidden" name="rememberme" value="0">
      <button class="btn btn-primary btn-lg btn-block" type="submit">Conectar</button>
      <?php
      if ($this->messages) {
        echo '<ul class="login-msg">';
        foreach ($this->messages as $message) {
          echo '<li>' . $message . '</li>';
        }
        echo '</ul>';
      }
      ?>
    </div>
  </form>
</div>