<?php echo $this->doctype(); ?>
<html lang="es">

<head>
  <meta charset="utf-8">
  <?php echo $this->headTitle($this->translate('Pronoi'))->setSeparator(' - ')->setAutoEscape(false) ?>

  <?php echo $this->headMeta()
    ->appendName('viewport', 'width=device-width, initial-scale=1.0')
    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
  ?>

  <!-- Styles -->
  <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
    ->prependStylesheet($this->basePath('/css/style.css'))
    ->prependStylesheet($this->basePath('/css/bootstrap-theme.css'))
    ->prependStylesheet($this->basePath('/css/bootstrap.min.css'))
    ->prependStylesheet($this->basePath('/css/elegant-icons-style.css'))
    ->prependStylesheet($this->basePath('/css/font-awesome.min.css'))
    ->prependStylesheet($this->basePath('/assets/fullcalendar/fullcalendar/bootstrap-fullcalendar.css'))
    ->prependStylesheet($this->basePath('/assets/fullcalendar/fullcalendar/fullcalendar.css'))
    ->prependStylesheet($this->basePath('/assets/jquery-easy-pie-chart/jquery.easy-pie-chart.css'))
    ->prependStylesheet($this->basePath('/css/owl.carousel.css'))
    ->prependStylesheet($this->basePath('/css/jquery-jvectormap-1.2.2.css'))
    ->prependStylesheet($this->basePath('/css/fullcalendar.css'))
    ->prependStylesheet($this->basePath('/css/widgets.css'))
    ->prependStylesheet($this->basePath('/css/style.css'))
    ->prependStylesheet($this->basePath('/css/style-responsive.css'))
    ->prependStylesheet($this->basePath('/css/xcharts.min.css'))
    ->prependStylesheet($this->basePath('/css/dataTables.bootstrap.css'))
    ->prependStylesheet($this->basePath('/css/jquery-ui-1.10.4.min.css'))
    ->prependStylesheet($this->basePath('/css/animate.css'));
  ?>

  <!-- Scripts -->
  <?php echo $this->headScript()
    ->prependFile($this->basePath('/js/bootstrap.min.js'))
    ->prependFile($this->basePath('/js/jquery.min.js'))
    ->prependFile($this->basePath('/js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
    ->prependFile($this->basePath('/js/html5shiv.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
    ->prependFile($this->basePath('/js/lte-ie7.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
    ->prependFile($this->basePath('/js/respond.min.js'));
  ?>

  <?php
    use Application\Model\Application;
    $session = new \Zend\Session\Container('user');
    $user = $session->user;
  ?>

  <script type="text/javascript" charset="utf-8">
    // Roles JS
    var ROL_ADMINISTRADOR                       = <?php echo Application::ROL_ADMINISTRADOR ?>;
    var ROL_ADMINISTRADOR_PLANTILLAS            = <?php echo Application::ROL_ADMINISTRADOR_PLANTILLAS ?>;
    var ROL_ADMINISTRADOR_REPORTES              = <?php echo Application::ROL_ADMINISTRADOR_REPORTES ?>;
    var ROL_PERSONAL_NOMINA                     = <?php echo Application::ROL_PERSONAL_NOMINA ?>;
    var ROL_PERSONAL_RH                         = <?php echo Application::ROL_PERSONAL_RH ?>;
    var ROL_ADMINISTRADOR_ASISTENCIA            = <?php echo Application::ROL_ADMINISTRADOR_ASISTENCIA ?>;

    //Permisos Control Reporte
    var CONTROL_REPORTE_GENERAR                 = <?php echo Application::CONTROL_REPORTE_GENERAR ?>;
    var CONTROL_REPORTE_CONSULTAR               = <?php echo Application::CONTROL_REPORTE_CONSULTAR ?>;
    var CONTROL_REPORTE_AUTORIZAR_A_DIRECCION   = <?php echo Application::CONTROL_REPORTE_AUTORIZAR_A_DIRECCION ?>;
    var CONTROL_REPORTE_AUTORIZAR_A_NOMINA      = <?php echo Application::CONTROL_REPORTE_AUTORIZAR_A_NOMINA ?>;

    //Estados
    var REPORTE_ESTADO_CALCULANDO               = <?php echo Application::REPORTE_ESTADO_CALCULANDO ?>;
    var REPORTE_ESTADO_COMPLETADO               = <?php echo Application::REPORTE_ESTADO_COMPLETADO ?>;
    var REPORTE_ESTADO_AUTORIZADO_POR_GERENCIA  = <?php echo Application::REPORTE_ESTADO_AUTORIZADO_POR_GERENCIA ?>;
    var REPORTE_ESTADO_RECHAZADO_POR_GERENCIA   = <?php echo Application::REPORTE_ESTADO_RECHAZADO_POR_GERENCIA ?>;
    var REPORTE_ESTADO_AUTORIZADO_POR_DIRECCION = <?php echo Application::REPORTE_ESTADO_AUTORIZADO_POR_DIRECCION ?>;
    var REPORTE_ESTADO_RECHAZADO_POR_DIRECCION  = <?php echo Application::REPORTE_ESTADO_RECHAZADO_POR_DIRECCION ?>;

    // Constants
    var TIPO_REGLA_SQL                          = <?php echo Application::TIPO_REGLA_SQL ?>;
    var TIPO_FREGLA_RECURSIVA                   = <?php echo Application::TIPO_FREGLA_RECURSIVA ?>;
    var TIPO_REPETIR_CAMPO_FECHA                = <?php echo Application::TIPO_REPETIR_CAMPO_FECHA ?>;
    var TIPO_REPETIR_CAMPO_VECES                = <?php echo Application::TIPO_REPETIR_CAMPO_VECES ?>;
    var CAMPO_ACTIVO                            = <?php echo Application::CAMPO_ACTIVO ?>;
    var TIPO_CAMPO_CATALOGO                     = <?php echo Application::TIPO_CAMPO_CATALOGO ?>;
    var TIPO_CAMPO_REGLA                        = <?php echo Application::TIPO_CAMPO_REGLA ?>;
    var TIPO_CAMPO_VALOR                        = <?php echo Application::TIPO_CAMPO_VALOR ?>;
    var TIPO_CAMPO_DINAMICO                     = <?php echo Application::TIPO_CAMPO_DINAMICO ?>;
    var TIPO_EXP_CAMPO                          = <?php echo Application::TIPO_EXP_CAMPO ?>;
    var TIPO_EXP_REGLA                          = <?php echo Application::TIPO_EXP_REGLA ?>;
    var TIPO_EXP_NUMERO                         = <?php echo Application::TIPO_EXP_NUMERO ?>;
    var TIPO_EXP_OPERADOR                       = <?php echo Application::TIPO_EXP_OPERADOR ?>;
    var TIPO_EXP_PUNTO                          = <?php echo Application::TIPO_EXP_PUNTO ?>;
    var TIPO_EXP_PARENT_IZQ                     = <?php echo Application::TIPO_EXP_PARENT_IZQ ?>;
    var TIPO_EXP_PARENT_DER                     = <?php echo Application::TIPO_EXP_PARENT_DER ?>;
    var TIPO_EXP_EMPLEADO                       = <?php echo Application::TIPO_EXP_EMPLEADO ?>;

    // Asistencia
    var ASISTENCIA_ASISTENCIA                   = <?php echo Application::ASISTENCIA_ASISTENCIA ?>;
    var ASISTENCIA_RETARDO                      = <?php echo Application::ASISTENCIA_RETARDO ?>;
    var ASISTENCIA_FALTA                        = <?php echo Application::ASISTENCIA_FALTA ?>;
    var ASISTENCIA_DESCANSO                     = <?php echo Application::ASISTENCIA_DESCANSO ?>;
    var ASISTENCIA_INCAPACIDAD                  = <?php echo Application::ASISTENCIA_INCAPACIDAD ?>;
    var ASISTENCIA_VACACIONES                   = <?php echo Application::ASISTENCIA_VACACIONES ?>;
    var ASISTENCIA_FESTIVO                      = <?php echo Application::ASISTENCIA_FESTIVO ?>;

    // Tolerancia
    var TOLERANCIA                              = <?php echo Application::TOLERANCIA ?>;

  </script>

</head>

<body>

<?php if (isset($user)) { ?>

  <input type="hidden" id="id_usuario" name="id_usuario" value="<?php echo $user['id']; ?>"/>
  <input type="hidden" id="id_tipo_empleado" name="id_tipo_empleado" value="<?php echo $user['id_tipo_empleado']; ?>"/>
  <input type="hidden" id="id_rol_usuario" name="id_rol_usuario" value="<?php echo $user['id_rol_usuario']; ?>"/>

  <!-- container section start -->
  <section id="container" class="">

    <header class="header dark-bg">

      <div class="toggle-nav">
        <div class="icon-reorder tooltips" data-original-title="Toggle Navigation" data-placement="bottom"></div>
      </div>

      <div class="row">
        <div class="col-md-4">
          <!--logo start-->
          <a href="/inicio" class="logo"><img alt="avatar" src="/images/logo-promass.png"></a>
          <!--logo end-->
          <div class="nav search-row" id="top_menu">
            <!--  search form start -->
            <!--                    <ul class="nav top-menu">-->
            <!--                        <li>-->
            <!--                            <form class="navbar-form">-->
            <!--                                <input class="form-control" placeholder="Buscar" type="text">-->
            <!--                            </form>-->
            <!--                        </li>-->
            <!--                    </ul>-->
            <!--  search form end -->
          </div>
        </div>
        <div class="col-md-7">
          <div class="username-row">
            <i class="glyphicon glyphicon-user"></i>
            <!--                    <span class="username">&nbsp; -->
            <?php echo $user['nombre']; ?> &nbsp;</span>
<!--            <span class="username">&nbsp; --><?php //print_r($user); ?><!-- &nbsp;</span>-->
            <a href="<?php echo $this->url('login/process', array('action' => 'logout')); ?>"><i
                class="logout icon_lock-open"></i></a>
          </div>
        </div>
      </div>

    </header>
    <!--header end-->

    <!--sidebar start-->
    <aside>
      <div id="sidebar" class="nav-collapse ">
        <!-- sidebar menu start-->
        <ul class="sidebar-menu">
          <li>
            <a href="/inicio">
              <i class="icon_house"></i>
              <span>Inicio</span>
            </a>
          </li>
          <?php if ($user['id_rol_usuario'] == Application::ROL_ADMINISTRADOR || $user['id_rol_usuario'] == Application::ROL_PERSONAL_RH) { ?>
            <li>
              <a href="javascript:;">
                <i class="icon_group"></i>
                <span>Usuarios</span>
              </a>
            </li>
            <li>
              <a href="javascript:;">
                <i class="icon_flowchart"></i>
                <span>Unid. de Negocio</span>
              </a>
            </li>
            <li>
              <a href="/empleados">
                <i class="icon_id-2_alt"></i>
                <span>Empleados</span>
              </a>
            </li>
          <?php } ?>
          <?php if ($user['id_rol_usuario'] ==  Application::ROL_ADMINISTRADOR
            || $user['id_rol_usuario'] ==  Application::ROL_ADMINISTRADOR_PLANTILLAS
            || $user['id_rol_usuario'] ==  Application::ROL_ADMINISTRADOR_REPORTES) { ?>
            <li>
              <a href="/plantillas">
                <i class="icon_table"></i>
                <span>Plantillas</span>
              </a>
            </li>
          <?php } ?>
          <?php if ($user['id_rol_usuario'] ==  Application::ROL_ADMINISTRADOR
            || $user['id_rol_usuario'] ==  Application::ROL_ADMINISTRADOR_ASISTENCIA) { ?>
            <li>
              <a href="/asistencia">
                <i class="icon_calendar"></i>
                <span>Asistencia</span>
              </a>
            </li>
          <?php } ?>
        </ul>
        <!-- sidebar menu end-->
      </div>
    </aside>
    <!--sidebar end-->

    <!--main content start-->
    <section id="main-content">
      <section class="wrapper">
        <!--overview start-->
        <div class="row">
          <div class="col-lg-12">
            <?php
            echo $this->navigation('navigation')->breadcrumbs()
              ->setMinDepth(0)->setLinkLast(true)->setPartial('breadcrumb');
            ?>
          </div>
        </div>

        <?php echo $this->content; ?>
      </section>
    </section>
    <!--main content end-->
  </section>
  <!-- container section start -->

  <div role="dialog" tabindex="-1" id="spinner" class="modal fade">
    <div class="modal-dialog spinner">
      <i class="fa fa-spinner fa-spin"></i>
    </div>
  </div>

<?php } else {
  echo $this->content;
} ?>

<!-- nice scroll -->
<script src="/js/jquery.scrollTo.min.js"></script>
<script src="/js/jquery.nicescroll.js"></script>

<!-- jquery validate js -->
<script src="/js/jquery.validate.min.js"></script>

<script src="/js/jquery.slimscroll.min.js"></script>
<script src="/js/jquery.dataTables.min.js"></script>
<script src="/js/dataTables.colReorder.js"></script>
<script src="/js/dataTables.bootstrap.js"></script>
<script src="/js/notify.js"></script>

<script src="/js/spinner.js"></script>
<script src="/js/message.engine.js"></script>
<script src="/js/ajax.js"></script>
<script src="/js/scripts.js"></script>

</body>
</html>
