<link rel="stylesheet" href="css/daterangepicker.css"/>

<script type="text/javascript" src="js/jquery.validate.min.js"></script>
<script src="js/moment.js"></script>
<script src="js/daterangepicker.js"></script>

<script type="text/javascript" charset="utf-8">
  $(document).ready(function () {

    $("#usuario_form").validate({
      rules: {
        nombre: {
          required: true,
          minlength: 5,
          remote: {
            url: "usuario/checkName",
            type: "POST",
            async: false,
            data: {
              id_usuario: function () {
                return $("#id_usuario_update").val();
              },
              nombre: function () {
                return $("#nombre").val();
              }
            }
          }
        },
        password: {
          required: true
        },
        id_rol_usuario: {
          required: true
        }
      },
      messages: {
        nombre: {
          required: "Ingrese un nombre para la usuario.",
          minlength: "El nombre de la usuario debe contener al menos 5 carácteres.",
          remote: "El nombre no se encuentra disponible."
        },
        password: {
          required: "Ingrese una contraseña."
        },
        id_rol_usuario: {
          required: "Seleccione un rol del usuario."
        }
      },
      invalidHandler: function (form, validator) {
        var errors = validator.numberOfInvalids();
        if (errors) {
          validator.errorList[0].element.focus();
        }
      }
    });

    $.executeFetch({
     action: "usuario/fetchAllRoles",
      method: "POST",
      dataType: "json",
      success: function (data) {
        var html = "<option value=''>Seleccionar</option>";
        data.forEach(function (rol) {
          html += "<option value='" + rol.id + "'>" + rol.nombre + "</option>";
        });
        $("#id_rol_usuario_update").html(html);
      },
      errorMsg: "Ocurrió un error al obtener la usuario."
    });

    var fetch = function () {
      $.executeFetch({
       action: "usuario/fetch",
        data: {id_usuario: $("#id_usuario_update").val()},
        method: "POST",
        dataType: "json",
        success: function (data) {
          console.log(data);
          $("#headerSection").html(data.nombre);
          $("#usuarioBC").html(data.nombre);
          $("#usuarioBC").attr("href", "usuario?id=" + data.id);

          $("#id_empleado").val(data.id_empleado);
          $("#empleado").val(data.empleado);
          $("#nombre").val(data.nombre);
          $("#password").val(data.password);
          $("#id_rol_usuario_update").val(data.id_rol_usuario);
        },
        errorMsg: "Ocurrió un error al obtener la usuario."
      });
    }

    if ($("#id_usuario_update").val() != "0") {
      $("#passwordDiv").hide();
      fetch();
    }

    $("#addUsuarioBT").click(function (e) {
      $.executePostValid({
        form: $("#usuario_form"),
       action: "usuario/update",
        method: "POST",
        dataType: "json",
        success: function (data) {
          location.href = "usuarios";
        },
        successMsg: "Usuario guardado.",
        errorMsg: "Ocurrió un error al guardar el usuario."
      });
    });

  });
</script>

<div class="row">
  <div class="col-lg-12">

    <section class="panel">
      <header class="panel-heading" id="headerSection">
        Nuevo Usuario
      </header>
      <div class="panel-body">
        <div class="form">
          <form class="form-validate form-horizontal" id="usuario_form">

            <input type="hidden" id="id_usuario_update" name="id_usuario_update" value="<?php if ($id) {
              echo $id;
            } else {
              echo "0";
            } ?>"/>

            <input type="hidden" id="id_empleado" name="id_empleado" value="<?php if ($id_empleado) {
              echo $id_empleado;
            } ?>"/>

            <div class="form-group">
              <label class="control-label col-lg-2">Empleado <span class="required">*</span></label>
              <div class="col-lg-5">
                <input class="form-control" id="empleado" name="empleado" value="<?php if ($empleado) {
                  echo $empleado;
                } ?>" readonly/>
              </div>
            </div>

            <div class="form-group">
              <label class="control-label col-lg-2">Usuario <span class="required">*</span></label>
              <div class="col-lg-5">
                <input class="form-control" id="nombre" name="nombre" minlength="5" type="text" required/>
                <input class="hidden" id="fake_2" name="fake_2" value="">
              </div>
            </div>

            <div class="form-group" id="passwordDiv">
              <label class="control-label col-lg-2">Contraseña <span class="required">*</span></label>
              <div class="col-lg-5">
                <input class="hidden" type="password" id="fake_3" name="fake_3" value="">
                <input type="password" class="form-control" id="password" name="password" minlength="5" type="text" required/>
              </div>
            </div>

            <div class="form-group">
              <label class="control-label col-lg-2">Rol<span
                  class="required">*</span></label>
              <div class="col-lg-5">
                <select class="form-control" id="id_rol_usuario_update" name="id_rol_usuario_update" required>
                </select>
              </div>
            </div>

            <div class="form-group">
              <div class="col-lg-offset-2 col-lg-10">
                <button class="btn btn-primary" type="button" id="addUsuarioBT">Guardar</button>
                <a class="btn btn-default" href="usuarios">Regresar</a>
              </div>
            </div>

          </form>
        </div>
      </div>
    </section>

  </div>
</div>

